// @flow

import Verify from "./Verify";

export { Verify };

export type VerifyType = {
  admin: boolean,
  customer: {
    billing_contact_id: string,
    billing_network_type: string,
    billing_ref: string,
    can_configure_wordpress: boolean,
    can_reset_passwords: boolean,
    can_upload_vcl: boolean,
    created_at: string,
    deleted_at: string,
    force_2fa: boolean,
    force_sso: boolean,
    has_account_panel: boolean,
    has_api_key: boolean,
    has_improved_events: boolean,
    has_improved_ssl_config: boolean,
    has_openstack_logging: boolean,
    has_pci: boolean,
    has_pci_passwords: boolean,
    id: string,
    ip_whitelist: string,
    logentries_provisioned_by: string,
    max_tokens_per_user: number,
    name: string,
    owner_id: string,
    phone_number: string,
    postal_address: string,
    pricing_plan: string,
    pricing_plan_id: string,
    rate_limit: number,
    readonly: boolean,
    requires_support_email: boolean,
    san_domains: number,
    updated_at: string,
  },
  features: string[],
  services: {
    [key: string]: string,
  },
  token: {
    created_at: string,
    customer_id: string,
    expires_at: string,
    id: string,
    ip: string,
    last_used_at: string,
    name: string,
    scope: string,
    scopes: string[],
    service_id: string,
    services: string[],
    sudo_expires_at: string,
    user_agent: string,
    user_id: string,
  },
  user: {
    created_at: string,
    customer_id: string,
    deleted_at: string,
    id: string,
    limit_services: boolean,
    locked: boolean,
    login: string,
    name: string,
    require_new_password: boolean,
    role: string,
    two_factor_auth_enabled: boolean,
    updated_at: string,
  },
};
